# -*- coding: utf-8 -*-
"""Projet PangaeaX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onxS89rl3gtIpuhqX1k7urTnxlAgS9Pf
"""

import pandas as pd

data= pd.read_excel("/content/drive/MyDrive/report_finance-summary_2025-11-02.xlsx")
data

data.shape

data.columns

data.info()

data.dtypes

data.isnull().sum()

data.columns = data.columns.str.strip().str.replace(" ", "_").str.replace("/", "")

data

data["Date"] = pd.to_datetime(data["Date"])

data.dtypes

data.isna().sum()

data.describe()

data["Year"] = data["Date"].dt.year
data["Month"] = data["Date"].dt.month
data["Month_name"] = data["Date"].dt.month_name()
data["Day"] = data["Date"].dt.day
data["Weekday"] = data["Date"].dt.day_name()

data["Net_Revenue"] =(data["Gross_sales"]- data["Discounts"]- data["Refunds__Returns"])

data["Total_Revenue"] = (data["Net_Revenue"]+ data["Taxes"])

data["Other_Revenue"] = (data["Gift_card_sales"]+ data["Service_charges"]+ data["Tips"])

data["Total_Payments"] = (data["Cash"]+ data["TD_POS"]+ data["Fresha_online"]+ data["Fresha_terminal"])

data["Discount_Rate"] = (data["Discounts"] / data["Gross_sales"]) * 100

data["Refund_Rate"] = (data["Refunds__Returns"] / data["Gross_sales"]) * 100

data

#Total Revenue

total_revenue = data["Total_Revenue"].sum()
print("Total Revenue:", total_revenue)

#Total Discounts

total_discounts = data["Discounts"].sum()
print("Total Discounts:", total_discounts)

#Total Refunds

total_refunds = data["Refunds__Returns"].sum()
print("Total Refunds:", total_refunds)

#Net Revenue

net_revenue = data["Net_Revenue"].sum()
print("Net Revenue:", net_revenue)

#Total Taxes

total_taxes = data["Taxes"].sum()
print("Total Taxes:", total_taxes)

#payment_methods

payment_methods = data[[
    "Cash",
    "Fresha_online",
    "TD_POS",
    "Fresha_terminal"
]].sum()
print(payment_methods)

"""The business performance analysis shows that total revenue during the analyzed period reached approximately 187,042, while net revenue after discounts and refunds amounted to about 169,544. This indicates that discounts represent roughly 7.5% of total sales, which has a noticeable impact on overall profitability. In contrast, the total value of refunds remains very low (around 642), suggesting a high level of customer satisfaction and consistent service quality.
The payment behavior analysis also reveals a strong reliance on digital payment channels, with online payments accounting for the largest share of total transactions, while cash payments represent only a small portion of the revenue. This pattern indicates that customers strongly prefer online booking and digital payments.
Overall, the data suggests solid financial performance with opportunities to further improve profitability by optimizing the discount strategy and strengthening digital booking and payment experiences. These findings provide valuable insights for strategic decision-making and business growth within the scope of Business Analytics.
"""

# Visualizations

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Total Revenue vs Net Revenue vs Discounts vs Refunds

kpi_values = {
    "Total Revenue": total_revenue,
    "Net Revenue": net_revenue,
    "Total Discounts": abs(total_discounts),
    "Total Refunds": abs(total_refunds)
}

plt.figure(figsize=(8,5))
sns.barplot(x=list(kpi_values.keys()), y=list(kpi_values.values()), palette="viridis")
plt.title("Business KPIs Overview")
plt.ylabel("Amount")
plt.show()

"""📈Insight

This chart presents a strong and healthy financial structure. Total Revenue stands at approximately 175,000, with Net Revenue at around 160,000. Discounts and Refunds together account for only about 5.7% of total revenue, which is significantly lower than the industry average (typically 10–15% in premium services). The extremely low refund rate (~1%) indicates high customer satisfaction and consistent service quality. The minimal discount usage suggests the business relies on brand strength and value rather than price promotions, reflecting strong customer loyalty and pricing power.

💡Recommendation

Increase prices on high-demand services by 5–10% to boost revenue without losing customers.
· Market your low refund rate as a trust signal in ads or social media (e.g., "99% customer satisfaction").
· Review current discounts to ensure they serve a clear purpose (e.g., attracting new clients or filling slow hours), not just random offers.
"""

# Payment Methods Pie Chart

payment_df = payment_methods.reset_index()
payment_df.columns = ['Payment Method', 'Revenue']

fig = px.pie(payment_df,
             names='Payment Method',
             values='Revenue',
             title='Revenue Distribution by Payment Method',
             color_discrete_sequence=px.colors.qualitative.Pastel,
             hole=0.3)
fig.show()

"""#📈Insight
This pie chart reveals a heavy reliance on digital/Fresha ecosystem payments, with Fresha_terminal accounting for 59.9% of total revenue, followed by TD_POS at 32%. Together, these two digital payment methods represent nearly 92% of all transactions. Cash payments make up only 7.49%, while Fresha_online is minimal at 0.574%. This distribution clearly indicates that customers strongly prefer cashless, seamless payment experiences, which aligns perfectly with a premium barbershop's target clientele who value convenience and speed. The very low online booking payments suggest that most clients either book in person or through other channels, but ultimately pay via terminal at the shop. This data confirms that the business has successfully transitioned to a modern, digital-first payment environment, reducing cash handling risks and improving operational efficiency.

💡Recommendation

Promote Fresha_online more aggressively: The 0.574% share is extremely low. Consider offering a small incentive (e.g., 5% off first online booking) to encourage digital pre-booking and payment, which would improve cash flow and reduce in-store wait times.

✅ Reduce cash dependency further: 7.49% cash is already low, but you can push toward 5% by adding a small convenience fee for cash payments or a discount for digital payments. This also improves security and reduces end-of-day reconciliation work.

✅ Leverage Fresha ecosystem for loyalty programs: Since 92% of payments go through Fresha, use this platform to build a digital loyalty program. Send automated thank-you messages, birthday discounts, or re-engagement offers to customers based on their payment history.

✅ Train staff to encourage digital: Ensure your team gently reminds customers about the benefits of digital payment (speed, rewards, receipts via email) at the point of sale.
"""

# Revenue Over Time

data['Date'] = pd.to_datetime(data['Date'])
data['YearMonth'] = data['Date'].dt.to_period('M')
monthly_revenue = data.groupby('YearMonth')['Total_Revenue'].sum().reset_index()
monthly_revenue['YearMonth'] = monthly_revenue['YearMonth'].astype(str)

fig = px.line(monthly_revenue, x='YearMonth', y='Total_Revenue',
              title='Monthly Total Revenue',
              markers=True)
fig.update_layout(xaxis_title="Month", yaxis_title="Revenue")
fig.show()

"""📈Insight

The chart shows a clear upward trend in revenue from November 2024 to September 2025. Revenue started at ~10,000 in November 2024 and grew steadily to ~20,000 in September 2025, achieving 100% total growth. This consistent increase reflects:

· Growing customer base and brand loyalty
· Effective marketing strategies
· Improved market reputation
· Strong customer retention with new client acquisition

The steady growth without sharp fluctuations indicates operational stability and sound financial management.

💡Recommendation

Continue current growth strategies as they are proving effective
· Analyze revenue jumps between January-March 2025 (seasonal or campaign success) and leverage insights for future planning
· Set ambitious target of 25,000 by end of 2025 through: new services, extended hours, customer referral program
· Monitor any signs of slowdown in coming months and prepare quick interventions
· Compare this trend with same period last year to determine real annual growth rate
"""

# Net Revenue vs Total Revenue Over Time

monthly_kpi = data.groupby('YearMonth')[['Total_Revenue','Net_Revenue']].sum().reset_index()
monthly_kpi['YearMonth'] = monthly_kpi['YearMonth'].astype(str)

fig = go.Figure()
fig.add_trace(go.Scatter(x=monthly_kpi['YearMonth'], y=monthly_kpi['Total_Revenue'],
                         mode='lines+markers', name='Total Revenue'))
fig.add_trace(go.Scatter(x=monthly_kpi['YearMonth'], y=monthly_kpi['Net_Revenue'],
                         mode='lines+markers', name='Net Revenue'))
fig.update_layout(title='Revenue vs Net Revenue Over Time',
                  xaxis_title='Month', yaxis_title='Amount')
fig.show()

"""📈Insight

The chart shows two parallel trends for Total Revenue and Net Revenue from November 2024 to September 2025. The gap between the lines remains relatively constant throughout the period, indicating that discounts and refunds maintain stability even as revenue grows. This is a positive indicator of:

· Consistent discount policies without increase during growth
· Effective financial control preventing profit leakage
· Stable service quality minimizing refunds

Both lines rise together at roughly the same pace, meaning growth in Total Revenue directly translates to growth in Net Revenue without erosion from discounts.

💡Recommendation


· Maintain current discount policies as they prove effective for balanced growth
· Monitor the gap monthly - if it widens, it's an early warning of increasing discounts or refunds
· Use this chart in presentations to demonstrate financial management efficiency to the client
· Calculate monthly discount/refund percentage (gap between lines) to ensure it stays below 5-7%
"""

# Discounts and Refunds Impact

discount_refund = pd.DataFrame({
    'Type': ['Discounts', 'Refunds'],
    'Amount': [abs(total_discounts), abs(total_refunds)]
})

sns.barplot(x='Type', y='Amount', data=discount_refund, palette="rocket")
plt.title("Impact of Discounts and Refunds")
plt.ylabel("Amount")
plt.show()

"""📈Insight

The chart shows a clear comparison between total Discounts and total Refunds. Discounts are significantly higher than refunds, indicating that discounts are the main tool used to stimulate sales or reward customers, while refunds are very low reflecting strong customer satisfaction. This distribution is normal and healthy in the service industry, where discounts are expected to be higher than refunds. The low refund rate confirms consistent service quality and customers receiving value for their money.

💡Recommendation


Analyze discount effectiveness: Do they drive sales growth or just represent additional cost?
· Use discounts strategically: Focus them on slow periods or for new customer acquisition
· Maintain low refunds: Continue staff training and quality monitoring
· Calculate discount-to-revenue ratio: Should not exceed 5-7% to maintain profitability
"""

discount_refund_month = data.groupby('YearMonth')[['Discounts','Refunds__Returns']].sum().reset_index()


discount_refund_month[['Discounts', 'Refunds__Returns']] = discount_refund_month[['Discounts', 'Refunds__Returns']].abs()

discount_refund_month['YearMonth'] = discount_refund_month['YearMonth'].astype(str)

fig = px.bar(discount_refund_month, x='YearMonth', y=['Discounts','Refunds__Returns'],
             title='Monthly Discounts & Refunds Impact',
             labels={'value':'Amount','variable':'Type'},
             barmode='stack', color_discrete_sequence=px.colors.qualitative.Pastel)
fig.show()

"""📈Insight

The chart shows the distribution of Discounts versus Refunds from November 2024 to September 2025. Discounts are consistently higher than refunds across most months, with a notable peak in the middle period (March-May 2025). This indicates:

· Intensive promotional campaigns during this period leading to increased discounts
· Refunds remain low and stable despite higher discounts, confirming service quality
· Positive correlation between higher discounts and increased revenue (as seen in previous charts)

💡Recommendation


Analyze the March-May 2025 period: What happened? Was there a successful marketing campaign?
· Use this seasonal pattern to plan similar campaigns for the coming year
· Ensure discount increases correspond to revenue increases (calculate ROI for each campaign)
· Monitor refunds in months following intensive discount campaigns to ensure service quality
"""

data['WeekPart'] = data['Weekday'].apply(lambda x: 'Weekend' if x in ['Saturday','Sunday'] else 'Weekday')
week_revenue = data.groupby('WeekPart')['Total_Revenue'].sum().reset_index()

fig = px.bar(week_revenue, x='WeekPart', y='Total_Revenue',
             title='Revenue: Weekday vs Weekend',
             color='Total_Revenue', color_continuous_scale='Viridis')
fig.show()

"""📈Insight


The chart shows a clear comparison between Weekday revenue and Weekend revenue. Weekday revenue is approximately 136,277, while Weekend revenue is approximately 50,765. This means:

· Weekdays capture ~73% of total revenue
· Weekend captures only ~27% of revenue
· Significant gap favoring weekdays, indicating that the target audience consists of customers who visit during regular workdays

This distribution is normal in the premium barbershop sector, where clients are often employees and executives who prefer grooming before workdays or during breaks

💡Recommendation


Focus marketing efforts on weekdays as they are the main revenue source
· Develop special weekend offers to boost revenue on slower days (e.g., "Weekend special: haircut + free care")
· Analyze peak hours within weekdays to optimize staff scheduling
· Consider extending weekday hours to capitalize on high demand
· Use this chart to plan advertising campaigns (target weekdays with intensive ads)
"""

monthly_revenue = data.groupby('YearMonth')['Total_Revenue'].sum().reset_index()
monthly_revenue['YearMonth'] = monthly_revenue['YearMonth'].dt.to_timestamp()


monthly_revenue['Revenue_Class'] = pd.qcut(monthly_revenue['Total_Revenue'], q=3, labels=['Low','Medium','High'])

fig = px.bar(monthly_revenue, x='YearMonth', y='Total_Revenue', color='Revenue_Class',
             title='Monthly Revenue Classification (Low/Medium/High)')
fig.show()

"""📈Insight

The chart shows monthly revenue classified into three categories: Low, Medium, and High from November 2024 to September 2025. It's clear that:

· Early months (November 2024 - January 2025) were in the Low revenue category (below 11,000)
· Middle months (March 2025 - May 2025) moved to the Medium revenue category (11,000 - 14,000)
· Recent months (July 2025 - September 2025) achieved the High revenue category (above 15,000)

This classification confirms gradual and sustainable revenue growth, with the business moving from one category to another consistently. The absence of sharp fluctuations indicates operational stability and effective growth strategies

💡Recommendation

Analyze transition reasons between categories: What changed in marketing strategies or services during these periods?
· Aim for "High" category every month by setting ambitious growth plans
· Use this classification to identify months needing additional marketing support
· Calculate growth rate between categories to determine business growth speed
· Share this chart with your team to motivate them to consistently achieve "High" category
"""

#Final Strategic Recommendations

"""Final Strategic Recommendations

==========================================

---

💰 Revenue Growth Strategies

1. Price Optimization

· Increase prices on top services by 5-10% gradually
· Why: Low refund rate (~1%) proves customers pay for quality
· Impact: +8,000–12,000 annual revenue

2. Weekday Focus

· Allocate 80% of marketing budget to weekdays (Sun-Thu)
· Why: Weekdays already generate 73% of revenue
· Impact: +15% growth in main revenue stream

3. Weekend Activation

· Launch "Weekend Special" : 15% family discount or free add-on
· Why: Weekends only 27% of revenue → huge opportunity
· Impact: +30–40% weekend revenue

---

📱 Digital Payment Strategies

4. Boost Fresha_online

· Offer 5% discount for first online booking (3 months)
· Why: Currently only 0.574% → massive untapped potential
· Impact: Increase to 5–7% of total revenue

5. Reduce Cash

· Train staff to highlight "faster, safer digital payment"
· Why: Cash is 7.49% → security risk & inefficiency
· Impact: Reduce cash to <4% in 6 months

6. Digital Loyalty Program

· Use Fresha for automated birthday offers & re-engagement
· Why: 92% digital payments → rich customer data unused
· Impact: +20% repeat visits

---

📈 Seasonal & Marketing Strategies

7. Leverage Peak Season (March-May)

· Plan intensive campaigns for March-May 2026 (repeat 2025 success)
· Why: This period showed highest growth in revenue & discounts
· Impact: Replicate +20% seasonal growth

8. Monthly Classification Strategy

· Allocate more marketing budget to "Low" months to upgrade them
· Why: Proven transition path: Low → Medium → High
· Impact: Reduce seasonality & stabilize revenue

---

👥 Operational Strategies

9. Staff Scheduling

· Analyze weekday peak hours and increase staff during busy times
· Why: Weekdays = 73% revenue → need higher capacity
· Impact: Reduce wait times & increase satisfaction

10. Quality Training

· Maintain monthly training to keep refund rate below 1%
· Why: Low refunds = key competitive advantage
· Impact: Protect premium brand reputation
"""











